services:
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: ran_symbio
      MYSQL_PASSWORD: symbio
      MYSQL_ROOT_PASSWORD: Symb1O
      MYSQL_DATABASE: symbio_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: