version: '3.8'

services:
  # ##############################
  # # Frontend Container (Development)
  # ##############################
  frontend:
    container_name: frontend
    image: frontend:dev
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  # ##############################
  # # Backend Container (Development)
  # ##############################
  backend:
    container_name: backend
    image: backend:dev
    build:
      dockerfile: go.dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    depends_on:
      - db

  ##############################
  # Database Container
  ##############################
  db:
    restart: always
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Symb1O
      MYSQL_DATABASE: symbio_db
      MYSQL_USER: ran_symbio
      MYSQL_PASSWORD: symbio
    ports:
      - "3306:3306"
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pSymb1O"]
      interval: 1m
      timeout: 30s
      retries: 30

networks:
  mynet:
    driver: bridge
